apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    "helm.sh/hook": pre-delete
spec:
  restartPolicy: Never
  containers:
    - name: c1
      image: alpine
      command: [ "sleep","20" ]
