apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    containers:
      - name: nginx
        image: nginx
        env5: {{- toYaml .Values.env | nindent 10 }}
         {{- with .Values.env }}
        env: {{- toYaml . | nindent 10 }}
         {{- end }}
        env1:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        env2:
        {{- range $key, $value := .Values.env2 }}
          - name: {{ $key }}
            value: {{ $value }}
        {{- end }}

