apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  annotations:
    "helm.sh/hook": pre-install
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: demo-job
          image: busybox:latest
          command: ["/bin/sh", "-c", "echo 'Running job'"]
      restartPolicy: Never